INSERT INTO grocery.csv VALUES (1, “Aluminum Foil”, 8.84, miscellaneous);
INSERT INTO grocery.csv VALUES (2, “Apples”, 10.81, produce);
INSERT INTO grocery.csv VALUES (3, "Bacon", 9.01, meat);
INSERT INTO grocery.csv VALUES (4, "Bagels", 10.67, bread);
INSERT INTO grocery.csv VALUES (5, "Baguette/French Bread", 5.02 bread);
INSERT INTO grocery.csv VALUES (6, "Barbeque", 16.96, packaged);
INSERT INTO grocery.csv VALUES (7, "Butter", 4.29, dairy);
INSERT INTO grocery.csv VALUES (8, "Carrots", 2.88, produce);
INSERT INTO grocery.csv VALUES (9, "Cheese", 1.75, dairy);
INSERT INTO grocery.csv VALUES (10, "Coffee", 6.17, packaged);
INSERT INTO grocery.csv VALUES (11, "Cod Cuts", 1.47, deli);
INSERT INTO grocery.csv VALUES (12, "Cream Cheese", 16.11, dairy);
INSERT INTO grocery.csv VALUES (13, "Croissants", 6.36, bread);
INSERT INTO grocery.csv VALUES (14, "Eggs", 2.66, dairy);
INSERT INTO grocery.csv VALUES (15, "Fish", 0.49, meat);
INSERT INTO grocery.csv VALUES (16, "Flour", 8.74, bulk);
INSERT INTO grocery.csv VALUES (17, "Fruit", 8.87, produce);
INSERT INTO grocery.csv VALUES (18, "Grapes", 8.78, produce);
INSERT INTO grocery.csv VALUES (19, "Green Beans", 7.86, produce);
INSERT INTO grocery.csv VALUES (20, "Ground Beef", 16.03, meat);
INSERT INTO grocery.csv VALUES (21, "Ham", 13.37, meat);
INSERT INTO grocery.csv VALUES (22, "Honey", 9.31, packaged);
INSERT INTO grocery.csv VALUES (23, "Ice Cream", 14.08, frozen);
INSERT INTO grocery.csv VALUES (24, "Ketchup", 2.94, packaged);
INSERT INTO grocery.csv VALUES (25, "Lemons", 17.24, produce);
INSERT INTO grocery.csv VALUES (26, "Lettuce", 16.28, produce);
INSERT INTO grocery.csv VALUES (27, "Milk", 2.34, dairy);
INSERT INTO grocery.csv VALUES (28, "Mushrooms", 16.68, produce);
INSERT INTO grocery.csv VALUES (29, "Oil", 5.25, packaged);
INSERT INTO grocery.csv VALUES (30, "Onions", 1.11 produce);
INSERT INTO grocery.csv VALUES (31, "Orange Juice", 2.52, frozen);
INSERT INTO grocery.csv VALUES (32, "Oranges", 3.40, produce);
INSERT INTO grocery.csv VALUES (33, "Pasta", 13.39, bulk);
INSERT INTO grocery.csv VALUES (34, "Pizza", 16.61, frozen);
INSERT INTO grocery.csv VALUES (35, "Potatoes", 13.29, produce);
INSERT INTO grocery.csv VALUES (36, "Rice", 5.23, bulk);
INSERT INTO grocery.csv VALUES (37, "Salami", 12.70, meat);
INSERT INTO grocery.csv VALUES (38, "Soda", 11.21, miscellaneous);
INSERT INTO grocery.csv VALUES (39, "Sour Cream", 1.73, dairy);
INSERT INTO grocery.csv VALUES (40, "Tomatoes", 1.56, produce);
INSERT INTO grocery.csv VALUES (41, "Yogurt", 18.67, dairy);
